# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hazzik's blog
tagline:          ''
description:      ''
url:              https://hazzik.github.io
timezone:         'NZS-12:00'
tag_page_layout: tag_page
tag_page_dir: tag

author:
  name:           'Alex Zaytsev'
  url:            https://hazzik.github.io

paginate:         5

github:
  source:    'http://github.com/hazzik/hazzik.github.io/edit/master/'

ya_metrika_id:    25093751

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

exclude:
  - vendor